{% set name = "napari-stl-exporter" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jo-mueller/napari-stl-exporter/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 833844548beb5bde0555dde475ea6a0f7a35a253bdb63d438479d527486762ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - napari
    - napari-plugin-engine >=0.1.4
    - npe2
    - numpy
    - python >={{ python_min }}
    - scikit-image
    - vedo >=2023.4.6

test:
  commands:
    - pip list
    - pip check || true
    - xvfb-run -a python -c "import napari_stl_exporter; print('import OK')"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jo-mueller/napari-stl-exporter
  summary: Exports label images to 3D-printable stl files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jo-mueller
